export const mailData = [
    {
        'title': 'article',
        'author': 'Designmodo',
        'time': '02 april, 14',
        'attach': true,
        'isActive': false,
        'isUnread': true,
    },
    {
        'title': 'Startup 2016',
        'author': 'Maxime Messer',
        'time': '09 Oct, 16',
        'attach': false,
        'isActive': false,
        'isUnread': true,
    },
    {
        'title': 'Updates from Kevin',
        'author': 'Goodreads',
        'time': 'Yesterday',
        'attach': false,
        'isActive': false,
        'isUnread': true,
    },
    {
        'title': 'Top Stories of the Day',
        'author': 'TechCrunch',
        'time': 'Yesterday',
        'attach': false,
        'isActive': false,
        'isUnread': false,
    },
    {
        'title': 'Narcos Season 2',
        'author': 'Netflix',
        'time': '07:35 PM',
        'attach': false,
        'isActive': false,
        'isUnread': false,
    },
    {
        'title': 'Interview with Shopify',
        'author': 'Aisha Dialo',
        'time': '12:05 PM',
        'attach': false,
        'isActive': false,
        'isUnread': false,
    },
    {
        'title': 'Nextmail New Look',
        'author': 'Salman Shah',
        'time': '11:00 AM',
        'attach': true,
        'isActive': true,
        'isUnread': false,
    },
    {
        'title': 'Design Language',
        'author': 'Salman Shah',
        'time': '08:00 PM',
        'attach': false,
        'isActive': false,
        'isUnread': false,
    }];